[build]
  base = "packages/frontend"
  command = "npm run build"
  publish = "packages/frontend/dist"

[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/demo"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/index.html"
  status = 200
